include_defs('//bucklets/maven_jar.bucklet')

maven_jar(
  name = 'gerrit.gitms.shared',
  id = 'com.wandisco.gerrit.gitms.shared:gerrit.gitms.shared:1.0.2-SNAPSHOT',
  bin_sha1 = 'f5aa318bda4c6c8d688c9d00b90681dcd82ce636',
  src_sha1 = '9700be0d0a331691654a8e901943c9a74e33c5fc',
  license = 'Apache2.0',
  repository = REPO_WD,
  unsign = True
)
